[schematic2]
uniq 29
[tools]
[detail]
w 2042 -1173 100 0 n#1 aomDatumAll.aomDatumAll#284.VAL 1552 -912 1872 -912 1872 -1184 2272 -1184 esels.bdValsSel.INPK
w 1642 -789 100 0 n#2 aomDatumAll.aomDatumAll#284.FLNK 1552 -800 1792 -800 junction
w 1522 -1093 100 0 n#2 esels.bdValsSela.FLNK 1264 -1104 1840 -1104 1840 -1248 2272 -1248 esels.bdValsSel.SLNK
w 1730 -586 100 0 n#2 aomParkAll.aomParkAll#283.FLNK 1552 -512 1728 -512 1728 -720 1792 -720 junction
w 3090 -922 100 0 n#2 efanouts.fan.LNK2 3616 -208 3760 -208 3760 -528 3088 -528 3088 -1376 2240 -1376 2240 -1248 junction
w 2442 130 100 0 n#2 aomProbe.aomProbe#281.MECHLNK 2960 352 3024 352 3024 128 1920 128 junction
w 3642 34 100 0 n#2 aomProbe.aomProbe#282.MECHLNK 4128 336 4192 336 4192 32 3152 32 3152 256 3024 256 junction
w 1922 -130 100 0 n#2 aomProbe.aomProbe#280.MECHLNK 1872 352 1920 352 1920 -672 1792 -672 1792 -1104 junction
w 770 -1212 100 0 n#3 aomSystem.aomSystem#279.FLNK 704 -1216 896 -1216 896 -1344 976 -1344 esels.bdValsSela.SLNK
w 858 -981 100 0 n#4 aomSystem.aomSystem#279.VAL 704 -1280 800 -1280 800 -992 976 -992 esels.bdValsSela.INPB
w 1938 -1214 100 0 n#5 aomParkAll.aomParkAll#283.VAL 1552 -624 1664 -624 1664 -1216 2272 -1216 esels.bdValsSel.INPL
w 1642 -1134 100 0 n#6 esels.bdValsSela.VAL 1264 -1136 2080 -1136 2080 -1120 2192 -1120 2192 -928 2272 -928 esels.bdValsSel.INPC
w 2114 -570 100 0 n#7 aomProbe.aomProbe#282.MECHSTAT 4128 368 4224 368 4224 -64 3136 -64 3136 -48 2112 -48 2112 -1152 2272 -1152 esels.bdValsSel.INPJ
w 2228 -482 100 0 n#8 aomProbe.aomProbe#281.MECHSTAT 2960 384 3040 384 3040 96 2224 96 2224 -1120 2272 -1120 esels.bdValsSel.INPI
w 2130 -322 100 0 n#9 aomProbe.aomProbe#280.MECHSTAT 1872 384 2128 384 2128 -1088 2272 -1088 esels.bdValsSel.INPH
w 2514 -78 100 0 n#10 aomProbe.aomProbe#280.LSEL 1872 480 2096 480 2096 -80 2992 -80 ecalcs.calc.INPA
w 3170 82 100 0 n#11 esels.bdValsSel.INPG 2272 -1056 2240 -1056 2240 80 4160 80 4160 240 4128 240 aomProbe.aomProbe#282.CARSTAT
w 2474 50 100 0 n#12 aomProbe.aomProbe#281.CARSTAT 2960 256 3008 256 3008 48 2000 48 2000 -592 2208 -592 2208 -1024 2272 -1024 esels.bdValsSel.INPF
w 1970 -146 100 0 n#13 aomProbe.aomProbe#280.CARSTAT 1872 256 1968 256 1968 -608 2160 -608 2160 -992 2272 -992 esels.bdValsSel.INPE
w 2282 290 100 0 n#14 aomProbe.aomProbe#280.FLNK 1872 512 2144 512 2144 288 2480 288 aomProbe.aomProbe#281.SLNK
w 3234 -794 100 0 n#15 eaos.bdValOut.OUT 2944 -1072 3232 -1072 3232 -576 3472 -576 ecars.activeC.IVAL
w 2602 -974 100 0 n#16 esels.bdValsSel.VAL 2560 -1040 2592 -1040 2592 -976 2672 -976 2672 -1008 2688 -1008 eaos.bdValOut.DOL
w 2562 -1006 100 0 n#17 esels.bdValsSel.FLNK 2560 -1008 2624 -1008 2624 -1040 2688 -1040 eaos.bdValOut.SLNK
w 3490 2 100 0 n#18 aomProbe.aomProbe#282.FLNK 4128 496 4240 496 4240 0 2800 0 2800 -464 2992 -464 ecalcs.calc.SLNK
w 1442 -14 100 0 n#19 efanouts.startFan.FLNK 1600 -80 1664 -80 1664 -16 1280 -16 1280 288 1392 288 aomProbe.aomProbe#280.SLNK
w 1258 -158 100 0 n#20 ebos.startLoop.VAL 1216 -160 1360 -160 efanouts.startFan.SDIS
w 3394 274 100 0 n#21 aomProbe.aomProbe#281.FLNK 2960 512 3200 512 3200 272 3648 272 aomProbe.aomProbe#282.SLNK
w 3490 -30 100 0 n#22 aomProbe.aomProbe#282.LSEL 4128 464 4176 464 4176 -32 2864 -32 2864 -144 2992 -144 ecalcs.calc.INPC
w 3058 286 100 0 n#23 aomProbe.aomProbe#281.LSEL 2960 480 3056 480 3056 32 2832 32 2832 -112 2992 -112 ecalcs.calc.INPB
w 3562 498 100 0 n#24 hwin.hwin#177.in 3536 496 3648 496 aomProbe.aomProbe#282.PROBE
w 2418 514 100 0 n#25 hwin.hwin#174.in 2416 512 2480 512 aomProbe.aomProbe#281.PROBE
w 1298 514 100 0 n#26 hwin.hwin#171.in 1264 512 1392 512 aomProbe.aomProbe#280.PROBE
w 3282 -238 100 0 n#27 ecalcs.calc.FLNK 3280 -240 3344 -240 3344 -256 3376 -256 efanouts.fan.SLNK
w 3338 -174 100 0 n#28 ecalcs.calc.VAL 3280 -272 3312 -272 3312 -176 3424 -176 efanouts.fan.SELL
s 3824 -1520 100 0 Gemini Telescope Control System
s 3008 1216 100 0 $Id: aom.sch,v 1.4 2010/11/29 14:17:26 cjm Exp $
s 3856 -1664 100 0 A & G subsystem simulator
s 976 1120 100 0 CHOP selects the chop state to follow
s 976 1168 100 0 For each Guide probe symbol
s 976 1088 100 0 DATA contains the x,y,z demand for each chop state
s 976 944 100 0 These inputs are generated by the driveAG records
s 976 912 100 0 in the TCS
[cell use]
use bd200tr -608 -2024 -100 0 frame
xform 0 2032 -320
use aomDatumAll 1392 -969 100 0 aomDatumAll#284
xform 0 1472 -840
use aomParkAll 1392 -681 100 0 aomParkAll#283
xform 0 1472 -552
use aomProbe 3648 119 100 0 aomProbe#282
xform 0 3888 496
p 3728 224 100 0 -1 seta:prefix $(p3)
p 3728 176 100 0 -1 setb:wfn WF3
p 3728 32 100 0 0 setd:delay 3.0
use aomProbe 2480 135 100 0 aomProbe#281
xform 0 2720 512
p 2560 240 100 0 -1 seta:prefix $(p2)
p 2560 192 100 0 -1 setb:wfn WF2
p 2560 48 100 0 0 setd:delay 3.0
use aomProbe 1392 135 100 0 aomProbe#280
xform 0 1632 512
p 1472 240 100 0 -1 seta:prefix $(p1)
p 1472 192 100 0 -1 setb:wfn WF1
p 1472 48 100 0 0 setd:delay 3.0
use aomSystem 480 -1401 100 0 aomSystem#279
xform 0 592 -1280
use eaos 2712 -1128 100 0 bdValOut
xform 0 2816 -1040
p 2432 -1058 100 0 0 OMSL:closed_loop
p 2432 -1634 100 0 0 PV:$(aom)
p 2944 -1072 75 768 -1 pproc(OUT):PP
use esels 1000 -1416 100 0 bdValsSela
xform 0 1120 -1152
p 1056 -1106 100 0 -1 SELM:High Signal
p 1088 -1424 100 1024 0 name:$(aom)$(I)
use esels 2296 -1320 100 0 bdValsSel
xform 0 2416 -1056
p 2049 -1451 100 0 0 PV:$(aom)
p 2352 -1010 100 0 -1 SELM:High Signal
use simSwitch 936 56 100 0 simSwitch#233
xform 0 1072 224
p 896 16 100 0 1 seta:scanloc $(top)$(subsys)startFan.SCAN
use efanouts 1384 -328 100 0 startFan
xform 0 1480 -176
p 1246 89 100 0 0 DESC:Probe fanout
p 1216 -18 100 0 0 DISV:0
p 1216 -980 100 0 0 PV:$(aom)
p 1360 -274 100 0 -1 SCAN:.05 second
use efanouts 3400 -392 100 0 fan
xform 0 3496 -240
p 3262 25 100 0 0 DESC:Triggers Move completion
p 3232 -1044 100 0 0 PV:$(aom)
p 3232 -274 100 0 0 SELM:Mask
use ecars 3496 -856 100 0 activeC
xform 0 3632 -688
p 3463 -1608 100 0 0 PV:$(aom)
use hwin 3368 456 100 0 hwin#177
xform 0 3440 496
p 3347 488 100 0 -1 val(in):3
use hwin 2248 472 100 0 hwin#174
xform 0 2320 512
p 2227 504 100 0 -1 val(in):2
use hwin 1096 472 100 0 hwin#171
xform 0 1168 512
p 1075 504 100 0 -1 val(in):1
use ecalcs 3016 -552 100 0 calc
xform 0 3136 -288
p 3120 -338 100 0 -1 CALC:A|B|C
p 2769 -715 100 0 0 PV:$(aom)
use ebos 984 -248 100 0 startLoop
xform 0 1088 -160
p 728 -4 100 0 0 DESC:Disable/Enable simulation loop
p 640 -306 100 0 0 ONAM:enabled
p 660 -760 100 0 0 PV:$(aom)
p 640 -274 100 0 0 ZNAM:disabled
use eais 790 -553 100 0 FOC_offset
xform 0 856 -480
p 744 -417 100 0 -1 DESC:Focus offset from instrument
p 472 -738 100 0 0 EGU:mm
p 706 -553 100 0 -1 PV:$(aom)
[comments]
