TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

# Configuration data files are installed in $TOP)/data
#DATA += xxx.pv
DATA += gsaoivfilt1.lut
DATA += gsaoivfilt2.lut
DATA += GemNorth.default
DATA += GemNorth.current
DATA += GemNorthSIM.current
DATA += tcsSimulations.default
DATA += tcsSimulationsMK.default
DATA += startSeq
DATA += startSeqSIM
DATA += tcsM1Restore.pv
DATA += tcsM1RestoreAO.pv
DATA += tcsM1Model.save
DATA += tcs.subs
DATA += tc1.subs
DATA += sim.subs
DATA += disableInterlocking.default
DATA += procserv-softTCS_mk.service

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

